(*
    WARNING:
    This file is automatically generated.
    Any changes made here by hand will be overwritten!
*)

/// <summary>
/// List of Dockerfile syntax versions from 'dockerfile' repository.
/// </summary>
[<RequireQualifiedAccess>]
module Tuffenuff.DSL.Syntax

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.15-labs</c>
/// </summary>
/// <example>
/// <c>v1_15_labs</c> ->
/// <c># syntax=docker/dockerfile:1.15-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_15_labs = syntax "docker/dockerfile:1.15-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.15.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_15_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.15.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_15_0_labs = syntax "docker/dockerfile:1.15.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.15</c>
/// </summary>
/// <example>
/// <c>v1_15</c> ->
/// <c># syntax=docker/dockerfile:1.15</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_15 = syntax "docker/dockerfile:1.15"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.15.0</c>
/// </summary>
/// <example>
/// <c>v1_15_0</c> ->
/// <c># syntax=docker/dockerfile:1.15.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_15_0 = syntax "docker/dockerfile:1.15.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1-labs</c>
/// </summary>
/// <example>
/// <c>v1_labs</c> ->
/// <c># syntax=docker/dockerfile:1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_labs = syntax "docker/dockerfile:1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1</c>
/// </summary>
/// <example>
/// <c>v1</c> ->
/// <c># syntax=docker/dockerfile:1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1 = syntax "docker/dockerfile:1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.14-labs</c>
/// </summary>
/// <example>
/// <c>v1_14_labs</c> ->
/// <c># syntax=docker/dockerfile:1.14-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_14_labs = syntax "docker/dockerfile:1.14-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.14</c>
/// </summary>
/// <example>
/// <c>v1_14</c> ->
/// <c># syntax=docker/dockerfile:1.14</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_14 = syntax "docker/dockerfile:1.14"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.14.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_14_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.14.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_14_0_labs = syntax "docker/dockerfile:1.14.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.14.0</c>
/// </summary>
/// <example>
/// <c>v1_14_0</c> ->
/// <c># syntax=docker/dockerfile:1.14.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_14_0 = syntax "docker/dockerfile:1.14.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:labs</c>
/// </summary>
/// <example>
/// <c>labs</c> ->
/// <c># syntax=docker/dockerfile:labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let labs = syntax "docker/dockerfile:labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.13-labs</c>
/// </summary>
/// <example>
/// <c>v1_13_labs</c> ->
/// <c># syntax=docker/dockerfile:1.13-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_13_labs = syntax "docker/dockerfile:1.13-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.13.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_13_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.13.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_13_0_labs = syntax "docker/dockerfile:1.13.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.13</c>
/// </summary>
/// <example>
/// <c>v1_13</c> ->
/// <c># syntax=docker/dockerfile:1.13</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_13 = syntax "docker/dockerfile:1.13"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.13.0</c>
/// </summary>
/// <example>
/// <c>v1_13_0</c> ->
/// <c># syntax=docker/dockerfile:1.13.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_13_0 = syntax "docker/dockerfile:1.13.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_12_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.12.1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_1_labs = syntax "docker/dockerfile:1.12.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12-labs</c>
/// </summary>
/// <example>
/// <c>v1_12_labs</c> ->
/// <c># syntax=docker/dockerfile:1.12-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_labs = syntax "docker/dockerfile:1.12-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12</c>
/// </summary>
/// <example>
/// <c>v1_12</c> ->
/// <c># syntax=docker/dockerfile:1.12</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12 = syntax "docker/dockerfile:1.12"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12.1</c>
/// </summary>
/// <example>
/// <c>v1_12_1</c> ->
/// <c># syntax=docker/dockerfile:1.12.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_1 = syntax "docker/dockerfile:1.12.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12.0</c>
/// </summary>
/// <example>
/// <c>v1_12_0</c> ->
/// <c># syntax=docker/dockerfile:1.12.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_0 = syntax "docker/dockerfile:1.12.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_12_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.12.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_0_labs = syntax "docker/dockerfile:1.12.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11-labs</c>
/// </summary>
/// <example>
/// <c>v1_11_labs</c> ->
/// <c># syntax=docker/dockerfile:1.11-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_labs = syntax "docker/dockerfile:1.11-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_11_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.11.1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_1_labs = syntax "docker/dockerfile:1.11.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11</c>
/// </summary>
/// <example>
/// <c>v1_11</c> ->
/// <c># syntax=docker/dockerfile:1.11</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11 = syntax "docker/dockerfile:1.11"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11.1</c>
/// </summary>
/// <example>
/// <c>v1_11_1</c> ->
/// <c># syntax=docker/dockerfile:1.11.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_1 = syntax "docker/dockerfile:1.11.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11.0</c>
/// </summary>
/// <example>
/// <c>v1_11_0</c> ->
/// <c># syntax=docker/dockerfile:1.11.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_0 = syntax "docker/dockerfile:1.11.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_11_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.11.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_0_labs = syntax "docker/dockerfile:1.11.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.10-labs</c>
/// </summary>
/// <example>
/// <c>v1_10_labs</c> ->
/// <c># syntax=docker/dockerfile:1.10-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_10_labs = syntax "docker/dockerfile:1.10-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.10.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_10_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.10.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_10_0_labs = syntax "docker/dockerfile:1.10.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.10</c>
/// </summary>
/// <example>
/// <c>v1_10</c> ->
/// <c># syntax=docker/dockerfile:1.10</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_10 = syntax "docker/dockerfile:1.10"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.10.0</c>
/// </summary>
/// <example>
/// <c>v1_10_0</c> ->
/// <c># syntax=docker/dockerfile:1.10.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_10_0 = syntax "docker/dockerfile:1.10.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.9-labs</c>
/// </summary>
/// <example>
/// <c>v1_9_labs</c> ->
/// <c># syntax=docker/dockerfile:1.9-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_9_labs = syntax "docker/dockerfile:1.9-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.9.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_9_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.9.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_9_0_labs = syntax "docker/dockerfile:1.9.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.9</c>
/// </summary>
/// <example>
/// <c>v1_9</c> ->
/// <c># syntax=docker/dockerfile:1.9</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_9 = syntax "docker/dockerfile:1.9"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.9.0</c>
/// </summary>
/// <example>
/// <c>v1_9_0</c> ->
/// <c># syntax=docker/dockerfile:1.9.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_9_0 = syntax "docker/dockerfile:1.9.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8-labs</c>
/// </summary>
/// <example>
/// <c>v1_8_labs</c> ->
/// <c># syntax=docker/dockerfile:1.8-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_labs = syntax "docker/dockerfile:1.8-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_8_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.8.1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_1_labs = syntax "docker/dockerfile:1.8.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8</c>
/// </summary>
/// <example>
/// <c>v1_8</c> ->
/// <c># syntax=docker/dockerfile:1.8</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8 = syntax "docker/dockerfile:1.8"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8.1</c>
/// </summary>
/// <example>
/// <c>v1_8_1</c> ->
/// <c># syntax=docker/dockerfile:1.8.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_1 = syntax "docker/dockerfile:1.8.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_8_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.8.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_0_labs = syntax "docker/dockerfile:1.8.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8.0</c>
/// </summary>
/// <example>
/// <c>v1_8_0</c> ->
/// <c># syntax=docker/dockerfile:1.8.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_0 = syntax "docker/dockerfile:1.8.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7-labs</c>
/// </summary>
/// <example>
/// <c>v1_7_labs</c> ->
/// <c># syntax=docker/dockerfile:1.7-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_labs = syntax "docker/dockerfile:1.7-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_7_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.7.1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_1_labs = syntax "docker/dockerfile:1.7.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7</c>
/// </summary>
/// <example>
/// <c>v1_7</c> ->
/// <c># syntax=docker/dockerfile:1.7</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7 = syntax "docker/dockerfile:1.7"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7.1</c>
/// </summary>
/// <example>
/// <c>v1_7_1</c> ->
/// <c># syntax=docker/dockerfile:1.7.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_1 = syntax "docker/dockerfile:1.7.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_7_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.7.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_0_labs = syntax "docker/dockerfile:1.7.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7.0</c>
/// </summary>
/// <example>
/// <c>v1_7_0</c> ->
/// <c># syntax=docker/dockerfile:1.7.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_0 = syntax "docker/dockerfile:1.7.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.6.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_6_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.6.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_6_0_labs = syntax "docker/dockerfile:1.6.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.6-labs</c>
/// </summary>
/// <example>
/// <c>v1_6_labs</c> ->
/// <c># syntax=docker/dockerfile:1.6-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_6_labs = syntax "docker/dockerfile:1.6-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.6</c>
/// </summary>
/// <example>
/// <c>v1_6</c> ->
/// <c># syntax=docker/dockerfile:1.6</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_6 = syntax "docker/dockerfile:1.6"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.6.0</c>
/// </summary>
/// <example>
/// <c>v1_6_0</c> ->
/// <c># syntax=docker/dockerfile:1.6.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_6_0 = syntax "docker/dockerfile:1.6.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.2-labs</c>
/// </summary>
/// <example>
/// <c>v1_5_2_labs</c> ->
/// <c># syntax=docker/dockerfile:1.5.2-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_2_labs = syntax "docker/dockerfile:1.5.2-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5-labs</c>
/// </summary>
/// <example>
/// <c>v1_5_labs</c> ->
/// <c># syntax=docker/dockerfile:1.5-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_labs = syntax "docker/dockerfile:1.5-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.2</c>
/// </summary>
/// <example>
/// <c>v1_5_2</c> ->
/// <c># syntax=docker/dockerfile:1.5.2</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_2 = syntax "docker/dockerfile:1.5.2"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5</c>
/// </summary>
/// <example>
/// <c>v1_5</c> ->
/// <c># syntax=docker/dockerfile:1.5</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5 = syntax "docker/dockerfile:1.5"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_5_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.5.1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_1_labs = syntax "docker/dockerfile:1.5.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.1</c>
/// </summary>
/// <example>
/// <c>v1_5_1</c> ->
/// <c># syntax=docker/dockerfile:1.5.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_1 = syntax "docker/dockerfile:1.5.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.0</c>
/// </summary>
/// <example>
/// <c>v1_5_0</c> ->
/// <c># syntax=docker/dockerfile:1.5.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_0 = syntax "docker/dockerfile:1.5.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_5_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.5.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_0_labs = syntax "docker/dockerfile:1.5.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.3-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_3_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4.3-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_3_labs = syntax "docker/dockerfile:1.4.3-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_labs = syntax "docker/dockerfile:1.4-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.3</c>
/// </summary>
/// <example>
/// <c>v1_4_3</c> ->
/// <c># syntax=docker/dockerfile:1.4.3</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_3 = syntax "docker/dockerfile:1.4.3"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4</c>
/// </summary>
/// <example>
/// <c>v1_4</c> ->
/// <c># syntax=docker/dockerfile:1.4</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4 = syntax "docker/dockerfile:1.4"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.2-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_2_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4.2-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_2_labs = syntax "docker/dockerfile:1.4.2-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.2</c>
/// </summary>
/// <example>
/// <c>v1_4_2</c> ->
/// <c># syntax=docker/dockerfile:1.4.2</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_2 = syntax "docker/dockerfile:1.4.2"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4.1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_1_labs = syntax "docker/dockerfile:1.4.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.1</c>
/// </summary>
/// <example>
/// <c>v1_4_1</c> ->
/// <c># syntax=docker/dockerfile:1.4.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_1 = syntax "docker/dockerfile:1.4.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_0_labs = syntax "docker/dockerfile:1.4.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.0</c>
/// </summary>
/// <example>
/// <c>v1_4_0</c> ->
/// <c># syntax=docker/dockerfile:1.4.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_0 = syntax "docker/dockerfile:1.4.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3-labs</c>
/// </summary>
/// <example>
/// <c>v1_3_labs</c> ->
/// <c># syntax=docker/dockerfile:1.3-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_labs = syntax "docker/dockerfile:1.3-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_3_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.3.1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_1_labs = syntax "docker/dockerfile:1.3.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3</c>
/// </summary>
/// <example>
/// <c>v1_3</c> ->
/// <c># syntax=docker/dockerfile:1.3</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3 = syntax "docker/dockerfile:1.3"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3.1</c>
/// </summary>
/// <example>
/// <c>v1_3_1</c> ->
/// <c># syntax=docker/dockerfile:1.3.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_1 = syntax "docker/dockerfile:1.3.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3.0</c>
/// </summary>
/// <example>
/// <c>v1_3_0</c> ->
/// <c># syntax=docker/dockerfile:1.3.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_0 = syntax "docker/dockerfile:1.3.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_3_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.3.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_0_labs = syntax "docker/dockerfile:1.3.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2-labs</c>
/// </summary>
/// <example>
/// <c>v1_2_labs</c> ->
/// <c># syntax=docker/dockerfile:1.2-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_labs = syntax "docker/dockerfile:1.2-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_2_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.2.1-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_1_labs = syntax "docker/dockerfile:1.2.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1-experimental</c>
/// </summary>
/// <example>
/// <c>v1_experimental</c> ->
/// <c># syntax=docker/dockerfile:1-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_experimental = syntax "docker/dockerfile:1-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:experimental</c>
/// </summary>
/// <example>
/// <c>experimental</c> ->
/// <c># syntax=docker/dockerfile:experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let experimental = syntax "docker/dockerfile:experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2.1</c>
/// </summary>
/// <example>
/// <c>v1_2_1</c> ->
/// <c># syntax=docker/dockerfile:1.2.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_1 = syntax "docker/dockerfile:1.2.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2</c>
/// </summary>
/// <example>
/// <c>v1_2</c> ->
/// <c># syntax=docker/dockerfile:1.2</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2 = syntax "docker/dockerfile:1.2"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2.0</c>
/// </summary>
/// <example>
/// <c>v1_2_0</c> ->
/// <c># syntax=docker/dockerfile:1.2.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_0 = syntax "docker/dockerfile:1.2.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_2_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.2.0-labs</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_0_labs = syntax "docker/dockerfile:1.2.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_experimental = syntax "docker/dockerfile:1.1-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.7-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_7_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.7-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_7_experimental = syntax "docker/dockerfile:1.1.7-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.7</c>
/// </summary>
/// <example>
/// <c>v1_1_7</c> ->
/// <c># syntax=docker/dockerfile:1.1.7</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_7 = syntax "docker/dockerfile:1.1.7"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1</c>
/// </summary>
/// <example>
/// <c>v1_1</c> ->
/// <c># syntax=docker/dockerfile:1.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1 = syntax "docker/dockerfile:1.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.6-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_6_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.6-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_6_experimental = syntax "docker/dockerfile:1.1.6-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.6</c>
/// </summary>
/// <example>
/// <c>v1_1_6</c> ->
/// <c># syntax=docker/dockerfile:1.1.6</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_6 = syntax "docker/dockerfile:1.1.6"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.5</c>
/// </summary>
/// <example>
/// <c>v1_1_5</c> ->
/// <c># syntax=docker/dockerfile:1.1.5</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_5 = syntax "docker/dockerfile:1.1.5"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.4</c>
/// </summary>
/// <example>
/// <c>v1_1_4</c> ->
/// <c># syntax=docker/dockerfile:1.1.4</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_4 = syntax "docker/dockerfile:1.1.4"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.5-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_5_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.5-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_5_experimental = syntax "docker/dockerfile:1.1.5-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.4-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_4_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.4-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_4_experimental = syntax "docker/dockerfile:1.1.4-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.3-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_3_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.3-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_3_experimental = syntax "docker/dockerfile:1.1.3-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.3</c>
/// </summary>
/// <example>
/// <c>v1_1_3</c> ->
/// <c># syntax=docker/dockerfile:1.1.3</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_3 = syntax "docker/dockerfile:1.1.3"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.1</c>
/// </summary>
/// <example>
/// <c>v1_1_1</c> ->
/// <c># syntax=docker/dockerfile:1.1.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_1 = syntax "docker/dockerfile:1.1.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.1-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_1_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.1-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_1_experimental = syntax "docker/dockerfile:1.1.1-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.0</c>
/// </summary>
/// <example>
/// <c>v1_1_0</c> ->
/// <c># syntax=docker/dockerfile:1.1.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_0 = syntax "docker/dockerfile:1.1.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.0-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_0_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.0-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_0_experimental = syntax "docker/dockerfile:1.1.0-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0-experimental</c>
/// </summary>
/// <example>
/// <c>v1_0_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.0-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_experimental = syntax "docker/dockerfile:1.0-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.2-experimental</c>
/// </summary>
/// <example>
/// <c>v1_0_2_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.0.2-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_2_experimental = syntax "docker/dockerfile:1.0.2-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.1-experimental</c>
/// </summary>
/// <example>
/// <c>v1_0_1_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.0.1-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_1_experimental = syntax "docker/dockerfile:1.0.1-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0</c>
/// </summary>
/// <example>
/// <c>v1_0</c> ->
/// <c># syntax=docker/dockerfile:1.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0 = syntax "docker/dockerfile:1.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.1</c>
/// </summary>
/// <example>
/// <c>v1_0_1</c> ->
/// <c># syntax=docker/dockerfile:1.0.1</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_1 = syntax "docker/dockerfile:1.0.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.0-experimental</c>
/// </summary>
/// <example>
/// <c>v1_0_0_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.0.0-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_0_experimental = syntax "docker/dockerfile:1.0.0-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.0</c>
/// </summary>
/// <example>
/// <c>v1_0_0</c> ->
/// <c># syntax=docker/dockerfile:1.0.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_0 = syntax "docker/dockerfile:1.0.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:0.9-experimental</c>
/// </summary>
/// <example>
/// <c>v0_9_experimental</c> ->
/// <c># syntax=docker/dockerfile:0.9-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v0_9_experimental = syntax "docker/dockerfile:0.9-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:0.9.0-experimental</c>
/// </summary>
/// <example>
/// <c>v0_9_0_experimental</c> ->
/// <c># syntax=docker/dockerfile:0.9.0-experimental</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v0_9_0_experimental = syntax "docker/dockerfile:0.9.0-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:0.9</c>
/// </summary>
/// <example>
/// <c>v0_9</c> ->
/// <c># syntax=docker/dockerfile:0.9</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v0_9 = syntax "docker/dockerfile:0.9"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:0.9.0</c>
/// </summary>
/// <example>
/// <c>v0_9_0</c> ->
/// <c># syntax=docker/dockerfile:0.9.0</c>
/// </example>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v0_9_0 = syntax "docker/dockerfile:0.9.0"
