(*
    WARNING:
    This file is automatically generated.
    Any changes made here by hand will be overwritten!
*)

/// <summary>
/// List of Dockerfile syntax versions from 'dockerfile' repository.
/// </summary>
[<RequireQualifiedAccess>]
module Tuffenuff.DSL.Syntax

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.15-labs</c>
/// </summary>
/// <example>
/// <c>v1_15_labs</c> ->
/// <c># syntax=docker/dockerfile:1.15-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2025-04-15T16:04:22
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_15_labs = syntax "docker/dockerfile:1.15-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.15.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_15_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.15.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2025-04-15T16:04:11
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_15_0_labs = syntax "docker/dockerfile:1.15.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.15</c>
/// </summary>
/// <example>
/// <c>v1_15</c> ->
/// <c># syntax=docker/dockerfile:1.15</c>
/// </example>
/// <remarks>
/// Last updated at 2025-04-15T16:03:46
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_15 = syntax "docker/dockerfile:1.15"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.15.0</c>
/// </summary>
/// <example>
/// <c>v1_15_0</c> ->
/// <c># syntax=docker/dockerfile:1.15.0</c>
/// </example>
/// <remarks>
/// Last updated at 2025-04-15T16:03:33
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_15_0 = syntax "docker/dockerfile:1.15.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1-labs</c>
/// </summary>
/// <example>
/// <c>v1_labs</c> ->
/// <c># syntax=docker/dockerfile:1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2025-03-06T12:39:37
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_labs = syntax "docker/dockerfile:1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1</c>
/// </summary>
/// <example>
/// <c>v1</c> ->
/// <c># syntax=docker/dockerfile:1</c>
/// </example>
/// <remarks>
/// Last updated at 2025-03-06T12:39:35
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1 = syntax "docker/dockerfile:1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.14-labs</c>
/// </summary>
/// <example>
/// <c>v1_14_labs</c> ->
/// <c># syntax=docker/dockerfile:1.14-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2025-03-06T12:39:27
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_14_labs = syntax "docker/dockerfile:1.14-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.14</c>
/// </summary>
/// <example>
/// <c>v1_14</c> ->
/// <c># syntax=docker/dockerfile:1.14</c>
/// </example>
/// <remarks>
/// Last updated at 2025-03-06T12:39:26
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_14 = syntax "docker/dockerfile:1.14"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.14.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_14_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.14.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2025-03-06T12:39:17
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_14_0_labs = syntax "docker/dockerfile:1.14.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.14.0</c>
/// </summary>
/// <example>
/// <c>v1_14_0</c> ->
/// <c># syntax=docker/dockerfile:1.14.0</c>
/// </example>
/// <remarks>
/// Last updated at 2025-03-06T12:39:16
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_14_0 = syntax "docker/dockerfile:1.14.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:labs</c>
/// </summary>
/// <example>
/// <c>labs</c> ->
/// <c># syntax=docker/dockerfile:labs</c>
/// </example>
/// <remarks>
/// Last updated at 2025-01-21T18:28:39
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let labs = syntax "docker/dockerfile:labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.13-labs</c>
/// </summary>
/// <example>
/// <c>v1_13_labs</c> ->
/// <c># syntax=docker/dockerfile:1.13-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2025-01-21T18:28:20
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_13_labs = syntax "docker/dockerfile:1.13-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.13.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_13_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.13.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2025-01-21T18:28:11
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_13_0_labs = syntax "docker/dockerfile:1.13.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.13</c>
/// </summary>
/// <example>
/// <c>v1_13</c> ->
/// <c># syntax=docker/dockerfile:1.13</c>
/// </example>
/// <remarks>
/// Last updated at 2025-01-21T18:28:10
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_13 = syntax "docker/dockerfile:1.13"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.13.0</c>
/// </summary>
/// <example>
/// <c>v1_13_0</c> ->
/// <c># syntax=docker/dockerfile:1.13.0</c>
/// </example>
/// <remarks>
/// Last updated at 2025-01-21T18:28:00
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_13_0 = syntax "docker/dockerfile:1.13.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_12_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.12.1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-12-17T00:20:17
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_1_labs = syntax "docker/dockerfile:1.12.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12-labs</c>
/// </summary>
/// <example>
/// <c>v1_12_labs</c> ->
/// <c># syntax=docker/dockerfile:1.12-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-12-17T00:20:13
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_labs = syntax "docker/dockerfile:1.12-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12</c>
/// </summary>
/// <example>
/// <c>v1_12</c> ->
/// <c># syntax=docker/dockerfile:1.12</c>
/// </example>
/// <remarks>
/// Last updated at 2024-12-17T00:19:23
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12 = syntax "docker/dockerfile:1.12"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12.1</c>
/// </summary>
/// <example>
/// <c>v1_12_1</c> ->
/// <c># syntax=docker/dockerfile:1.12.1</c>
/// </example>
/// <remarks>
/// Last updated at 2024-12-17T00:19:18
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_1 = syntax "docker/dockerfile:1.12.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12.0</c>
/// </summary>
/// <example>
/// <c>v1_12_0</c> ->
/// <c># syntax=docker/dockerfile:1.12.0</c>
/// </example>
/// <remarks>
/// Last updated at 2024-11-27T01:54:22
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_0 = syntax "docker/dockerfile:1.12.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.12.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_12_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.12.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-11-27T01:54:07
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_12_0_labs = syntax "docker/dockerfile:1.12.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11-labs</c>
/// </summary>
/// <example>
/// <c>v1_11_labs</c> ->
/// <c># syntax=docker/dockerfile:1.11-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-11-08T01:18:25
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_labs = syntax "docker/dockerfile:1.11-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_11_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.11.1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-11-08T01:18:21
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_1_labs = syntax "docker/dockerfile:1.11.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11</c>
/// </summary>
/// <example>
/// <c>v1_11</c> ->
/// <c># syntax=docker/dockerfile:1.11</c>
/// </example>
/// <remarks>
/// Last updated at 2024-11-08T01:18:20
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11 = syntax "docker/dockerfile:1.11"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11.1</c>
/// </summary>
/// <example>
/// <c>v1_11_1</c> ->
/// <c># syntax=docker/dockerfile:1.11.1</c>
/// </example>
/// <remarks>
/// Last updated at 2024-11-08T01:18:16
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_1 = syntax "docker/dockerfile:1.11.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11.0</c>
/// </summary>
/// <example>
/// <c>v1_11_0</c> ->
/// <c># syntax=docker/dockerfile:1.11.0</c>
/// </example>
/// <remarks>
/// Last updated at 2024-10-31T10:50:28
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_0 = syntax "docker/dockerfile:1.11.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.11.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_11_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.11.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-10-31T10:50:28
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_11_0_labs = syntax "docker/dockerfile:1.11.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.10-labs</c>
/// </summary>
/// <example>
/// <c>v1_10_labs</c> ->
/// <c># syntax=docker/dockerfile:1.10-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-09-11T07:16:32
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_10_labs = syntax "docker/dockerfile:1.10-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.10.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_10_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.10.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-09-11T07:16:28
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_10_0_labs = syntax "docker/dockerfile:1.10.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.10</c>
/// </summary>
/// <example>
/// <c>v1_10</c> ->
/// <c># syntax=docker/dockerfile:1.10</c>
/// </example>
/// <remarks>
/// Last updated at 2024-09-11T07:12:11
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_10 = syntax "docker/dockerfile:1.10"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.10.0</c>
/// </summary>
/// <example>
/// <c>v1_10_0</c> ->
/// <c># syntax=docker/dockerfile:1.10.0</c>
/// </example>
/// <remarks>
/// Last updated at 2024-09-11T07:12:07
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_10_0 = syntax "docker/dockerfile:1.10.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.9-labs</c>
/// </summary>
/// <example>
/// <c>v1_9_labs</c> ->
/// <c># syntax=docker/dockerfile:1.9-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-07-11T18:57:43
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_9_labs = syntax "docker/dockerfile:1.9-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.9.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_9_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.9.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-07-11T18:57:38
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_9_0_labs = syntax "docker/dockerfile:1.9.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.9</c>
/// </summary>
/// <example>
/// <c>v1_9</c> ->
/// <c># syntax=docker/dockerfile:1.9</c>
/// </example>
/// <remarks>
/// Last updated at 2024-07-11T18:57:31
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_9 = syntax "docker/dockerfile:1.9"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.9.0</c>
/// </summary>
/// <example>
/// <c>v1_9_0</c> ->
/// <c># syntax=docker/dockerfile:1.9.0</c>
/// </example>
/// <remarks>
/// Last updated at 2024-07-11T18:57:22
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_9_0 = syntax "docker/dockerfile:1.9.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8-labs</c>
/// </summary>
/// <example>
/// <c>v1_8_labs</c> ->
/// <c># syntax=docker/dockerfile:1.8-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-06-20T17:01:21
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_labs = syntax "docker/dockerfile:1.8-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_8_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.8.1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-06-20T17:01:15
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_1_labs = syntax "docker/dockerfile:1.8.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8</c>
/// </summary>
/// <example>
/// <c>v1_8</c> ->
/// <c># syntax=docker/dockerfile:1.8</c>
/// </example>
/// <remarks>
/// Last updated at 2024-06-20T16:58:33
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8 = syntax "docker/dockerfile:1.8"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8.1</c>
/// </summary>
/// <example>
/// <c>v1_8_1</c> ->
/// <c># syntax=docker/dockerfile:1.8.1</c>
/// </example>
/// <remarks>
/// Last updated at 2024-06-20T16:58:28
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_1 = syntax "docker/dockerfile:1.8.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_8_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.8.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-06-20T16:54:46
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_0_labs = syntax "docker/dockerfile:1.8.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.8.0</c>
/// </summary>
/// <example>
/// <c>v1_8_0</c> ->
/// <c># syntax=docker/dockerfile:1.8.0</c>
/// </example>
/// <remarks>
/// Last updated at 2024-06-11T18:45:33
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_8_0 = syntax "docker/dockerfile:1.8.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7-labs</c>
/// </summary>
/// <example>
/// <c>v1_7_labs</c> ->
/// <c># syntax=docker/dockerfile:1.7-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-04-25T18:48:25
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_labs = syntax "docker/dockerfile:1.7-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_7_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.7.1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-04-25T18:48:19
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_1_labs = syntax "docker/dockerfile:1.7.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7</c>
/// </summary>
/// <example>
/// <c>v1_7</c> ->
/// <c># syntax=docker/dockerfile:1.7</c>
/// </example>
/// <remarks>
/// Last updated at 2024-04-25T18:47:07
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7 = syntax "docker/dockerfile:1.7"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7.1</c>
/// </summary>
/// <example>
/// <c>v1_7_1</c> ->
/// <c># syntax=docker/dockerfile:1.7.1</c>
/// </example>
/// <remarks>
/// Last updated at 2024-04-25T18:47:02
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_1 = syntax "docker/dockerfile:1.7.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_7_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.7.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2024-03-06T16:43:06
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_0_labs = syntax "docker/dockerfile:1.7.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.7.0</c>
/// </summary>
/// <example>
/// <c>v1_7_0</c> ->
/// <c># syntax=docker/dockerfile:1.7.0</c>
/// </example>
/// <remarks>
/// Last updated at 2024-03-05T21:58:14
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_7_0 = syntax "docker/dockerfile:1.7.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.6.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_6_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.6.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2023-08-03T07:41:24
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_6_0_labs = syntax "docker/dockerfile:1.6.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.6-labs</c>
/// </summary>
/// <example>
/// <c>v1_6_labs</c> ->
/// <c># syntax=docker/dockerfile:1.6-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2023-07-13T00:21:09
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_6_labs = syntax "docker/dockerfile:1.6-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.6</c>
/// </summary>
/// <example>
/// <c>v1_6</c> ->
/// <c># syntax=docker/dockerfile:1.6</c>
/// </example>
/// <remarks>
/// Last updated at 2023-07-13T00:17:43
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_6 = syntax "docker/dockerfile:1.6"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.6.0</c>
/// </summary>
/// <example>
/// <c>v1_6_0</c> ->
/// <c># syntax=docker/dockerfile:1.6.0</c>
/// </example>
/// <remarks>
/// Last updated at 2023-07-13T00:17:39
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_6_0 = syntax "docker/dockerfile:1.6.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.2-labs</c>
/// </summary>
/// <example>
/// <c>v1_5_2_labs</c> ->
/// <c># syntax=docker/dockerfile:1.5.2-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2023-02-13T23:14:25
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_2_labs = syntax "docker/dockerfile:1.5.2-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5-labs</c>
/// </summary>
/// <example>
/// <c>v1_5_labs</c> ->
/// <c># syntax=docker/dockerfile:1.5-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2023-02-13T23:14:21
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_labs = syntax "docker/dockerfile:1.5-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.2</c>
/// </summary>
/// <example>
/// <c>v1_5_2</c> ->
/// <c># syntax=docker/dockerfile:1.5.2</c>
/// </example>
/// <remarks>
/// Last updated at 2023-02-13T23:14:17
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_2 = syntax "docker/dockerfile:1.5.2"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5</c>
/// </summary>
/// <example>
/// <c>v1_5</c> ->
/// <c># syntax=docker/dockerfile:1.5</c>
/// </example>
/// <remarks>
/// Last updated at 2023-02-13T23:14:13
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5 = syntax "docker/dockerfile:1.5"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_5_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.5.1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2023-01-30T18:23:42
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_1_labs = syntax "docker/dockerfile:1.5.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.1</c>
/// </summary>
/// <example>
/// <c>v1_5_1</c> ->
/// <c># syntax=docker/dockerfile:1.5.1</c>
/// </example>
/// <remarks>
/// Last updated at 2023-01-30T18:23:35
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_1 = syntax "docker/dockerfile:1.5.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.0</c>
/// </summary>
/// <example>
/// <c>v1_5_0</c> ->
/// <c># syntax=docker/dockerfile:1.5.0</c>
/// </example>
/// <remarks>
/// Last updated at 2023-01-17T22:25:22
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_0 = syntax "docker/dockerfile:1.5.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.5.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_5_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.5.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2023-01-17T22:23:22
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_5_0_labs = syntax "docker/dockerfile:1.5.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.3-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_3_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4.3-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2022-08-31T00:41:16
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_3_labs = syntax "docker/dockerfile:1.4.3-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2022-08-31T00:41:15
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_labs = syntax "docker/dockerfile:1.4-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.3</c>
/// </summary>
/// <example>
/// <c>v1_4_3</c> ->
/// <c># syntax=docker/dockerfile:1.4.3</c>
/// </example>
/// <remarks>
/// Last updated at 2022-08-31T00:40:59
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_3 = syntax "docker/dockerfile:1.4.3"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4</c>
/// </summary>
/// <example>
/// <c>v1_4</c> ->
/// <c># syntax=docker/dockerfile:1.4</c>
/// </example>
/// <remarks>
/// Last updated at 2022-08-31T00:40:57
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4 = syntax "docker/dockerfile:1.4"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.2-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_2_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4.2-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2022-05-06T18:12:40
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_2_labs = syntax "docker/dockerfile:1.4.2-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.2</c>
/// </summary>
/// <example>
/// <c>v1_4_2</c> ->
/// <c># syntax=docker/dockerfile:1.4.2</c>
/// </example>
/// <remarks>
/// Last updated at 2022-05-06T18:12:14
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_2 = syntax "docker/dockerfile:1.4.2"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4.1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2022-04-08T05:28:36
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_1_labs = syntax "docker/dockerfile:1.4.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.1</c>
/// </summary>
/// <example>
/// <c>v1_4_1</c> ->
/// <c># syntax=docker/dockerfile:1.4.1</c>
/// </example>
/// <remarks>
/// Last updated at 2022-04-08T05:28:04
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_1 = syntax "docker/dockerfile:1.4.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_4_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.4.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2022-03-09T20:55:17
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_0_labs = syntax "docker/dockerfile:1.4.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.4.0</c>
/// </summary>
/// <example>
/// <c>v1_4_0</c> ->
/// <c># syntax=docker/dockerfile:1.4.0</c>
/// </example>
/// <remarks>
/// Last updated at 2022-03-09T20:51:53
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_4_0 = syntax "docker/dockerfile:1.4.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3-labs</c>
/// </summary>
/// <example>
/// <c>v1_3_labs</c> ->
/// <c># syntax=docker/dockerfile:1.3-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2021-10-19T06:29:50
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_labs = syntax "docker/dockerfile:1.3-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_3_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.3.1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2021-10-19T06:29:48
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_1_labs = syntax "docker/dockerfile:1.3.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3</c>
/// </summary>
/// <example>
/// <c>v1_3</c> ->
/// <c># syntax=docker/dockerfile:1.3</c>
/// </example>
/// <remarks>
/// Last updated at 2021-10-19T06:29:35
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3 = syntax "docker/dockerfile:1.3"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3.1</c>
/// </summary>
/// <example>
/// <c>v1_3_1</c> ->
/// <c># syntax=docker/dockerfile:1.3.1</c>
/// </example>
/// <remarks>
/// Last updated at 2021-10-19T06:29:33
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_1 = syntax "docker/dockerfile:1.3.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3.0</c>
/// </summary>
/// <example>
/// <c>v1_3_0</c> ->
/// <c># syntax=docker/dockerfile:1.3.0</c>
/// </example>
/// <remarks>
/// Last updated at 2021-07-19T19:55:12
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_0 = syntax "docker/dockerfile:1.3.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.3.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_3_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.3.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2021-07-19T19:52:11
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_3_0_labs = syntax "docker/dockerfile:1.3.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2-labs</c>
/// </summary>
/// <example>
/// <c>v1_2_labs</c> ->
/// <c># syntax=docker/dockerfile:1.2-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2020-12-12T01:05:24
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_labs = syntax "docker/dockerfile:1.2-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2.1-labs</c>
/// </summary>
/// <example>
/// <c>v1_2_1_labs</c> ->
/// <c># syntax=docker/dockerfile:1.2.1-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2020-12-12T01:05:18
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_1_labs = syntax "docker/dockerfile:1.2.1-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1-experimental</c>
/// </summary>
/// <example>
/// <c>v1_experimental</c> ->
/// <c># syntax=docker/dockerfile:1-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2020-12-12T01:05:17
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_experimental = syntax "docker/dockerfile:1-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:experimental</c>
/// </summary>
/// <example>
/// <c>experimental</c> ->
/// <c># syntax=docker/dockerfile:experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2020-12-12T01:05:15
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let experimental = syntax "docker/dockerfile:experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2.1</c>
/// </summary>
/// <example>
/// <c>v1_2_1</c> ->
/// <c># syntax=docker/dockerfile:1.2.1</c>
/// </example>
/// <remarks>
/// Last updated at 2020-12-12T01:04:49
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_1 = syntax "docker/dockerfile:1.2.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2</c>
/// </summary>
/// <example>
/// <c>v1_2</c> ->
/// <c># syntax=docker/dockerfile:1.2</c>
/// </example>
/// <remarks>
/// Last updated at 2020-12-12T01:04:45
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2 = syntax "docker/dockerfile:1.2"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2.0</c>
/// </summary>
/// <example>
/// <c>v1_2_0</c> ->
/// <c># syntax=docker/dockerfile:1.2.0</c>
/// </example>
/// <remarks>
/// Last updated at 2020-12-08T06:10:05
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_0 = syntax "docker/dockerfile:1.2.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.2.0-labs</c>
/// </summary>
/// <example>
/// <c>v1_2_0_labs</c> ->
/// <c># syntax=docker/dockerfile:1.2.0-labs</c>
/// </example>
/// <remarks>
/// Last updated at 2020-12-08T06:04:51
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_2_0_labs = syntax "docker/dockerfile:1.2.0-labs"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2020-04-28T01:24:12
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_experimental = syntax "docker/dockerfile:1.1-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.7-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_7_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.7-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2020-04-28T01:24:10
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_7_experimental = syntax "docker/dockerfile:1.1.7-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.7</c>
/// </summary>
/// <example>
/// <c>v1_1_7</c> ->
/// <c># syntax=docker/dockerfile:1.1.7</c>
/// </example>
/// <remarks>
/// Last updated at 2020-04-28T01:22:23
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_7 = syntax "docker/dockerfile:1.1.7"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1</c>
/// </summary>
/// <example>
/// <c>v1_1</c> ->
/// <c># syntax=docker/dockerfile:1.1</c>
/// </example>
/// <remarks>
/// Last updated at 2020-04-28T01:20:31
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1 = syntax "docker/dockerfile:1.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.6-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_6_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.6-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2020-04-28T01:08:39
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_6_experimental = syntax "docker/dockerfile:1.1.6-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.6</c>
/// </summary>
/// <example>
/// <c>v1_1_6</c> ->
/// <c># syntax=docker/dockerfile:1.1.6</c>
/// </example>
/// <remarks>
/// Last updated at 2020-04-28T01:08:38
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_6 = syntax "docker/dockerfile:1.1.6"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.5</c>
/// </summary>
/// <example>
/// <c>v1_1_5</c> ->
/// <c># syntax=docker/dockerfile:1.1.5</c>
/// </example>
/// <remarks>
/// Last updated at 2020-02-24T21:45:04
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_5 = syntax "docker/dockerfile:1.1.5"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.4</c>
/// </summary>
/// <example>
/// <c>v1_1_4</c> ->
/// <c># syntax=docker/dockerfile:1.1.4</c>
/// </example>
/// <remarks>
/// Last updated at 2020-02-24T21:44:27
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_4 = syntax "docker/dockerfile:1.1.4"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.5-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_5_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.5-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2020-02-24T21:38:16
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_5_experimental = syntax "docker/dockerfile:1.1.5-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.4-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_4_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.4-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2020-02-24T21:21:53
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_4_experimental = syntax "docker/dockerfile:1.1.4-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.3-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_3_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.3-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2019-08-16T22:52:06
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_3_experimental = syntax "docker/dockerfile:1.1.3-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.3</c>
/// </summary>
/// <example>
/// <c>v1_1_3</c> ->
/// <c># syntax=docker/dockerfile:1.1.3</c>
/// </example>
/// <remarks>
/// Last updated at 2019-08-16T22:52:03
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_3 = syntax "docker/dockerfile:1.1.3"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.1</c>
/// </summary>
/// <example>
/// <c>v1_1_1</c> ->
/// <c># syntax=docker/dockerfile:1.1.1</c>
/// </example>
/// <remarks>
/// Last updated at 2019-05-06T22:42:55
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_1 = syntax "docker/dockerfile:1.1.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.1-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_1_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.1-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2019-05-06T22:33:21
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_1_experimental = syntax "docker/dockerfile:1.1.1-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.0</c>
/// </summary>
/// <example>
/// <c>v1_1_0</c> ->
/// <c># syntax=docker/dockerfile:1.1.0</c>
/// </example>
/// <remarks>
/// Last updated at 2019-04-27T02:20:50
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_0 = syntax "docker/dockerfile:1.1.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.1.0-experimental</c>
/// </summary>
/// <example>
/// <c>v1_1_0_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.1.0-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2019-04-27T02:14:14
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_1_0_experimental = syntax "docker/dockerfile:1.1.0-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0-experimental</c>
/// </summary>
/// <example>
/// <c>v1_0_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.0-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2019-02-26T01:52:27
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_experimental = syntax "docker/dockerfile:1.0-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.2-experimental</c>
/// </summary>
/// <example>
/// <c>v1_0_2_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.0.2-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2019-02-26T01:52:25
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_2_experimental = syntax "docker/dockerfile:1.0.2-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.1-experimental</c>
/// </summary>
/// <example>
/// <c>v1_0_1_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.0.1-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2018-12-11T18:43:53
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_1_experimental = syntax "docker/dockerfile:1.0.1-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0</c>
/// </summary>
/// <example>
/// <c>v1_0</c> ->
/// <c># syntax=docker/dockerfile:1.0</c>
/// </example>
/// <remarks>
/// Last updated at 2018-12-11T18:42:22
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0 = syntax "docker/dockerfile:1.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.1</c>
/// </summary>
/// <example>
/// <c>v1_0_1</c> ->
/// <c># syntax=docker/dockerfile:1.0.1</c>
/// </example>
/// <remarks>
/// Last updated at 2018-12-11T18:42:20
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_1 = syntax "docker/dockerfile:1.0.1"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.0-experimental</c>
/// </summary>
/// <example>
/// <c>v1_0_0_experimental</c> ->
/// <c># syntax=docker/dockerfile:1.0.0-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2018-11-08T00:32:27
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_0_experimental = syntax "docker/dockerfile:1.0.0-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:1.0.0</c>
/// </summary>
/// <example>
/// <c>v1_0_0</c> ->
/// <c># syntax=docker/dockerfile:1.0.0</c>
/// </example>
/// <remarks>
/// Last updated at 2018-11-08T00:31:03
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v1_0_0 = syntax "docker/dockerfile:1.0.0"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:0.9-experimental</c>
/// </summary>
/// <example>
/// <c>v0_9_experimental</c> ->
/// <c># syntax=docker/dockerfile:0.9-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2018-11-08T00:29:46
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v0_9_experimental = syntax "docker/dockerfile:0.9-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:0.9.0-experimental</c>
/// </summary>
/// <example>
/// <c>v0_9_0_experimental</c> ->
/// <c># syntax=docker/dockerfile:0.9.0-experimental</c>
/// </example>
/// <remarks>
/// Last updated at 2018-11-08T00:29:44
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v0_9_0_experimental = syntax "docker/dockerfile:0.9.0-experimental"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:0.9</c>
/// </summary>
/// <example>
/// <c>v0_9</c> ->
/// <c># syntax=docker/dockerfile:0.9</c>
/// </example>
/// <remarks>
/// Last updated at 2018-11-08T00:26:02
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v0_9 = syntax "docker/dockerfile:0.9"

/// <summary>
/// Sets the version of docker syntax to
/// <c>docker/dockerfile:0.9.0</c>
/// </summary>
/// <example>
/// <c>v0_9_0</c> ->
/// <c># syntax=docker/dockerfile:0.9.0</c>
/// </example>
/// <remarks>
/// Last updated at 2018-11-08T00:25:59
/// </remarks>
/// <seealso cref="Tuffenuff.DSL.Comments.syntax" />
let v0_9_0 = syntax "docker/dockerfile:0.9.0"
