name: Build and tests

on: 
  pull_request:

jobs:
  codestyle-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore tools
      run: dotnet tool restore

    - name: Codestyle check
      run: dotnet fake run build.fsx -t CodestyleCheck

  build-and-tests:
    needs: codestyle-check

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore tools
      run: dotnet tool restore

    - name: Run tests
      run: dotnet fake run build.fsx -t RunTests
