name: Build and tests

on: 
  pull_request:

jobs:
  codestyle-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore tools
      run: dotnet tool restore

    - name: Codestyle check
      run: ./run.sh CheckFormat

  build-and-tests:
    needs: codestyle-check

    strategy:
      fail-fast: false
      matrix:
        targets:
          - os: windows-latest
            script: .\run.cmd
          - os: macOS-latest
            script: ./run.sh
          - os: ubuntu-latest
            script: ./run.sh

    runs-on: ${{ matrix.targets.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Build project
      run: ${{ matrix.targets.script }} Build

    - name: Run unit tests
      run: ${{ matrix.targets.script }} UnitTests

    - name: Run integration tests
      run: ${{ matrix.targets.script }} IntegrationTests
