name: Build and tests

on: 
  push:
    paths-ignore:
    - '.config/**'
    - '.vscode/**'
    - 'docs/**'
    - 'imgs/**'
    - '*.md'
  pull_request:

jobs:
  build-and-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore tools
      run: dotnet tool restore

    - name: Run tests
      run: dotnet fake run build.fsx -t RunTests
