name: Build and tests

on: 
  pull_request:

jobs:
  codestyle-check:
    runs-on: ubuntu-latest

    name: Codestyle check

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore tools
      run: dotnet tool restore

    - name: Check format
      run: ./run.sh CheckFormat

  build-and-tests:
    needs: codestyle-check

    strategy:
      fail-fast: false
      matrix:
        targets:
          - os: windows-latest
            name: Windows
            script: .\run.cmd
          - os: macOS-latest
            name: macOS
            script: ./run.sh
          - os: ubuntu-latest
            name: Linux
            script: ./run.sh

    runs-on: ${{ matrix.targets.os }}

    name: Build and tests on ${{ matrix.targets.name }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Build
      run: ${{ matrix.targets.script }} Build

    - name: Unit tests
      run: ${{ matrix.targets.script }} UnitTests

    - name: Integration tests
      run: ${{ matrix.targets.script }} IntegrationTests
