name: Dev

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore tools
      run: dotnet tool restore

    - name: Build and Test
      run: dotnet fake run build.fsx -t RunTests
