name: Release

on:
  push:
    paths-ignore:
    - '.idea/**'
    - '.vscode/**'
    tags:
      - "*"

jobs:
  release-lib:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - run: |
        if [[ $GITHUB_REF_NAME == *"-"* ]]; then
          echo "PRE_RELEASE=true" >> $GITHUB_ENV
        else
          echo "PRE_RELEASE=false" >> $GITHUB_ENV
        fi

    - name: Github release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Nuget release
      env:
        KEY: ${{ secrets.NUGET_API_KEY }}
      run: ./run.sh Release -e NUGET_API_KEY=$KEY
